/// @file USBPDTask.h
///
/// @brief USBPD task — intentional hollow placeholder.
///
/// This task stub was generated by CubeMX and is kept for future use.
/// USB Power Delivery initialisation and processing are handled by
/// ManagerTask (via USBPDInitModule) and DeviceTask (via USBPDProcess)
/// respectively. This task blocks indefinitely and performs no work.
///
/// @copyright Copyright (c) 2026 Tim Hosking
/// @see https://github.com/munger
/// @par Licence: MIT

#ifndef USBPD_TASK_H
#define USBPD_TASK_H

#include "TaskUtils.h"

/// @brief FreeRTOS thread handle for the USBPD task stub.
extern osThreadId_t USBPDTaskHandle;

/// @brief Initialise the USBPD task stub (no-op).
void USBPDTaskInit( void );

/// @brief USBPD task loop — blocks indefinitely (intentional placeholder).
void USBPDTaskLoop( void );

#endif // USBPD_TASK_H
