#include <string.h>

#include "adc.h"
#include "main.h"
#include "spi.h"
#include "taskutils.h"
#include "thermistor.h"
#include "thermocouple.h"

// Reference the mutex generated by CubeMX for shared SPI access
extern osMutexId_t SPIBusMutexHandle;

typedef enum {
    RegCr0 = 0x00,
    RegCr1 = 0x01,
    RegMask = 0x02,
    RegCjhf = 0x03,
    RegCjlf = 0x04,
    RegLthfMsb = 0x05,
    RegCjto = 0x09,
    RegCjth = 0x0A,
    RegCjtl = 0x0B,
    RegLtcb2 = 0x0C,
    RegLtcb1 = 0x0D,
    RegLtcb0 = 0x0E,
    RegSr = 0x0F
} MaxRegister;

typedef enum {
    Cr0ConvModeAuto = 0x80,
    Cr0OneShot = 0x40,
    Cr0OcFault100Ms = 0x10,
    Cr0CjDisable = 0x08, // Disable internal cold junction sensor
    Cr1TypeK = 0x03
} MaxConfig;

struct Thermocouple {
    ThermocoupleID     id;
    ThermocoupleStatus status;
    GPIO_TypeDef*      csPort;
    uint16_t           csPin;
    uint16_t           drdyPin;
    uint16_t           faultPin;
    ThermistorID       externalCjtId;
    ThermistorRef      externalCjt;
    Temperature        lastTemp;
    TaskHandle_t       waitingTask;
    bool               dataReady;
};

static struct Thermocouple instances[ 2 ];

// Thread-safe register write to the MAX31856
static void TCWriteReg( ThermocoupleRef tc, MaxRegister reg, uint8_t val ) {
    uint8_t tx[ 2 ] = { (uint8_t)( (uint8_t)reg | 0x80 ), val };

    if ( osMutexAcquire( SPIBusMutexHandle, osWaitForever ) == osOK ) {
        HAL_GPIO_WritePin( tc->csPort, tc->csPin, GPIO_PIN_RESET );
        HAL_SPI_Transmit( &hspi1, tx, 2, 10 );
        HAL_GPIO_WritePin( tc->csPort, tc->csPin, GPIO_PIN_SET );
        osMutexRelease( SPIBusMutexHandle );
    }
}

// Thread-safe multi-register read from the MAX31856
static void TCReadRegs( ThermocoupleRef tc, MaxRegister reg, uint8_t* buffer, uint8_t len ) {
    uint8_t tx = (uint8_t)( (uint8_t)reg & 0x7F );

    if ( osMutexAcquire( SPIBusMutexHandle, osWaitForever ) == osOK ) {
        HAL_GPIO_WritePin( tc->csPort, tc->csPin, GPIO_PIN_RESET );
        HAL_SPI_Transmit( &hspi1, &tx, 1, 10 );
        HAL_SPI_Receive( &hspi1, buffer, len, 10 );
        HAL_GPIO_WritePin( tc->csPort, tc->csPin, GPIO_PIN_SET );
        osMutexRelease( SPIBusMutexHandle );
    }
}

// Initialise hardware mappings and configure chips for external CJT mode
void TCInitModule( void ) {
    memset( instances, 0, sizeof( instances ) );

    // Instance 1 Hardware Mapping
    instances[ Thermocouple1 ].id = Thermocouple1;
    instances[ Thermocouple1 ].csPort = THERM1_CS_GPIO_Port;
    instances[ Thermocouple1 ].csPin = THERM1_CS_Pin;
    instances[ Thermocouple1 ].drdyPin = THERM1_DRDY_Pin;
    instances[ Thermocouple1 ].faultPin = THERM1_FAULT_Pin;
    instances[ Thermocouple1 ].externalCjtId = ThermistorCJT1;

    // Instance 2 Hardware Mapping
    instances[ Thermocouple2 ].id = Thermocouple2;
    instances[ Thermocouple2 ].csPort = THERM2_CS_GPIO_Port;
    instances[ Thermocouple2 ].csPin = THERM2_CS_Pin;
    instances[ Thermocouple2 ].drdyPin = THERM2_DRDY_Pin;
    instances[ Thermocouple2 ].faultPin = THERM2_FAULT_Pin;
    instances[ Thermocouple2 ].externalCjtId = ThermistorCJT2;

    for ( uint8_t i = 0; i < 2; i++ ) {
        TCWriteReg( &instances[ i ], RegCr1, Cr1TypeK );
        TCWriteReg( &instances[ i ], RegCr0,
                    (uint8_t)Cr0ConvModeAuto | (uint8_t)Cr0OcFault100Ms | (uint8_t)Cr0CjDisable );
    }
}

// Retrieves the instance handle and links the associated CJT thermistor
ThermocoupleRef TCOpen( ThermocoupleID thermocoupleID ) {
    ThermocoupleRef tc = &instances[ (uint8_t)thermocoupleID ];

    if ( tc->externalCjt == NULL ) {
        tc->externalCjt = TMOpen( tc->externalCjtId );
    }

    return tc;
}

// Updates the MAX31856 with external CJT data and begins a conversion
void TCRequestSample( ThermocoupleRef tc ) {
    if ( tc == NULL || tc->externalCjt == NULL ) {
        return;
    }

    // Bulletproof Guard: If a conversion is already pending, do not reset state.
    // This allows safe calling from fast loops.
    if ( tc->waitingTask != NULL && !tc->dataReady ) {
        return;
    }

    tc->waitingTask = xTaskGetCurrentTaskHandle();
    tc->dataReady = false;

    // Read the board-level NTC to use as the cold junction reference
    Temperature cjt = TMGetTemperature( tc->externalCjt );
    int16_t     cj_bits = (int16_t)( ( cjt * 64 ) / 1000 );

    // Acquire mutex once to ensure both CJT bytes are written without bus interruption
    if ( osMutexAcquire( SPIBusMutexHandle, osWaitForever ) == osOK ) {
        uint8_t tx_h[ 2 ] = { (uint8_t)( (uint8_t)RegCjth | 0x80 ), (uint8_t)( ( cj_bits >> 8 ) & 0xFF ) };
        uint8_t tx_l[ 2 ] = { (uint8_t)( (uint8_t)RegCjtl | 0x80 ), (uint8_t)( cj_bits & 0xFF ) };

        HAL_GPIO_WritePin( tc->csPort, tc->csPin, GPIO_PIN_RESET );
        HAL_SPI_Transmit( &hspi1, tx_h, 2, 10 );
        HAL_GPIO_WritePin( tc->csPort, tc->csPin, GPIO_PIN_SET );

        HAL_GPIO_WritePin( tc->csPort, tc->csPin, GPIO_PIN_RESET );
        HAL_SPI_Transmit( &hspi1, tx_l, 2, 10 );
        HAL_GPIO_WritePin( tc->csPort, tc->csPin, GPIO_PIN_SET );

        osMutexRelease( SPIBusMutexHandle );
    }
}

// Returns the ready state of the current conversion
bool TCIsReady( ThermocoupleRef tc ) {
    return ( tc != NULL ) ? tc->dataReady : false;
}

// Returns temperature in milli-degrees; blocks task until the DRDY interrupt fires
Temperature TCGetTemperature( ThermocoupleRef tc ) {
    if ( tc == NULL )
        return 0;

    if ( !tc->dataReady ) {
        // Clear stale notifications to ensure we only wake on a fresh edge
        ulTaskNotifyValueClear( NULL, 0xFFFFFFFF );

        // Block until notified by ISR or timeout
        if ( ulTaskNotifyTake( pdTRUE, pdMS_TO_TICKS( 200 ) ) == 0 ) {
            // Cleanup on timeout
            tc->waitingTask = NULL;
            tc->status = TCStatusHardwareFault;
            return tc->lastTemp;
        }
    }

    // Success or already ready - clear handle for next cycle
    tc->waitingTask = NULL;

    uint8_t regs[ 3 ];
    TCReadRegs( tc, RegLtcb2, regs, 3 );

    // Assemble the 19-bit signed value from 3 bytes
    int32_t val = ( (int32_t)regs[ 0 ] << 16 ) | ( (int32_t)regs[ 1 ] << 8 ) | regs[ 2 ];
    if ( val & 0x800000 )
        val |= 0xFF000000;

    // Scaled to milli-degrees Celsius
    tc->lastTemp = ( val >> 5 ) * 1000 / 128;
    return tc->lastTemp;
}

// Returns the NTC cold junction temperature in milli-degrees
Temperature TCGetCJT( ThermocoupleRef tc ) {
    return ( tc != NULL && tc->externalCjt != NULL ) ? TMGetTemperature( tc->externalCjt ) : 0;
}

// Decodes the MAX31856 Fault Status register
ThermocoupleStatus TCGetStatus( ThermocoupleRef tc ) {
    if ( tc == NULL )
        return TCStatusHardwareFault;

    uint8_t sr;
    TCReadRegs( tc, RegSr, &sr, 1 );

    if ( sr & 0x01 )
        return TCStatusOpenCircuit;
    if ( sr & 0x02 )
        return TCStatusShortToGND;
    if ( sr & 0x04 )
        return TCStatusShortToVCC;
    if ( sr & 0x20 )
        return TCStatusCJTRangeHigh;
    if ( sr & 0x10 )
        return TCStatusCJTRangeLow;
    if ( sr & 0x80 )
        return TCStatusRangeHigh;
    if ( sr & 0x40 )
        return TCStatusRangeLow;

    return TCStatusOK;
}

// ISR Callback dispatcher to identify the source pin and wake the waiting task
void TCNotifyInterrupt( uint16_t pin ) {
    for ( uint8_t i = 0; i < 2; i++ ) {
        struct Thermocouple* tc = &instances[ i ];

        // Handle Data Ready signals
        if ( pin & tc->drdyPin ) {
            tc->dataReady = true;
            if ( tc->waitingTask != NULL ) {
                BaseType_t   xHigherPriorityTaskWoken = pdFALSE;

                // Copy handle and null immediately to prevent double-notification race
                TaskHandle_t taskToNotify = tc->waitingTask;
                tc->waitingTask = NULL;

                vTaskNotifyGiveFromISR( taskToNotify, &xHigherPriorityTaskWoken );
                portYIELD_FROM_ISR( xHigherPriorityTaskWoken );
            }
        }

        // Handle Hardware Fault signals
        if ( pin & tc->faultPin ) {
            tc->status = TCStatusHardwareFault;
        }
    }
}